apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: metrics
  namespace: monitoring
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  rules:
  - host: metrics.kafka.lulf.no
    http:
      paths:
      - backend:
          serviceName: prometheus-operated
          servicePort: web
        path: /
  tls:
  - hosts:
      - metrics.kafka.lulf.no
    secretName: monitoring-metrics-cert
