apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: sandbox-api
  namespace: sandbox
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  rules:
  - host: api.kafka.lulf.no 
    http:
      paths:
      - backend:
          serviceName: sandbox-api
          servicePort: http
        path: /
  tls:
  - hosts:
      - api.kafka.lulf.no
    secretName: api-cert
